# Apps
exec-once = discord
exec-once = spotify-launcher
exec-once = steam
exec-once = waybar

# Clipboard manager
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store

# Hypr polkit agent
exec-once = systemctl --user start hyprpolkitagent

# Hyprpaper
exec-once = hyprpaper

# OpenTableDriver daemon
exec-once = systemctl --user enable opentabletdriver.service --now
