[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-fps", "60", "--transition-type", "center"]
set = true

[templates.foot]
input_path = "~/.config/matugen/templates/foot.ini"
output_path = "~/.config/foot/matugen-colors.ini"

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/matugen-colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3" && gsettings set org.gnome.desktop.interface font-name "Inter 12" && gsettings set org.gnome.desktop.interface color-scheme "prefer-dark" && gsettings set org.gnome.desktop.interface icon-theme "Adwaita" && gsettings set org.gnome.desktop.interface cursor-theme "Bibata-Modern-Classic" && pkill nautilus'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/matugen-colors.css'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.config/hypr/source/matugen-colors.conf'
post_hook = 'hyprctl reload'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qtct.conf'
output_path = '~/.config/qt5ct/colors/matugen-colors.conf'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qtct.conf'
output_path = '~/.config/qt6ct/colors/matugen-colors.conf'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.config/rofi/matugen-colors.rasi'

[templates.spicetify]
input_path = '~/.config/matugen/templates/spicetify.ini'
output_path = '~/.config/spicetify/Themes/tui/color.ini'
post_hook = 'spicetify config inject_css 1 replace_colors 1 && spicetify config current_theme tui color_scheme matugen-colors && spicetify apply'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/matugen-colors.css'
post_hook = 'swaync-client -rs'

[templates.vencord]
input_path = '~/.config/matugen/templates/discord.css'
output_path = '~/.config/Vencord/themes/matugen-colors.css'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/matugen-colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.root]
input_path = '~/.config/matugen/templates/root.css'
output_path = '~/Downloads/matugen-colors.css'
