# Enable tearing
general {
    allow_tearing = true
}

# Set all steam games to fullscreen, ensure it's tearing and send it to workspace 10
windowrulev2 = fullscreen, class:^(steam_app_.*)$
windowrulev2 = immediate, class:^(steam_app_.*)$
windowrulev2 = workspace 10, class:^(steam_app_.*)$

# Special case, for some reason the class of CS2 is different from other steam games
windowrulev2 = fullscreen, class:^(cs2)$
windowrulev2 = immediate, class:^(cs2)$
windowrulev2 = workspace 10, class:^(cs2)$

# Set all games running with gamescope to fullscreen, ensure it's tearing and send it to workspace 10
windowrulev2 = fullscreen, class:gamescope
windowrulev2 = immediate, class:gamescope
windowrulev2 = workspace 10, class:gamescope

# Set minecraft to fullscreen, ensure it's tearing and send it to workspace 10
windowrulev2 = fullscreen, class:^(Minecraft.*)$
windowrulev2 = immediate, class:^(Minecraft.*)$
windowrulev2 = workspace 10, class:^(Minecraft.*)$

# Set osu! to fullscreen, ensure it's tearing and send it to workspace 10
windowrulev2 = fullscreen, class:^(osu!)$
windowrulev2 = immediate, class:^(osu!)$
windowrulev2 = workspace 10, class:^(osu!)$