# Auto Execute #

## Apps
exec-once = discord
exec-once = spotify-launcher
exec-once = steam
exec-once = waybar

## Clipboard manager

### Stores only text data
exec-once = wl-paste --type text --watch cliphist store 

### Stores only image data
exec-once = wl-paste --type image --watch cliphist store

## OpenTableDriver Daemon
exec-once = systemctl --user enable opentabletdriver.service --now

## Polkit agent
exec-once = systemctl --user start hyprpolkitagent

## Start wallpaper service
exec-once = hyprpaper
