input {
    # Keyboard
    ## Layouts
    kb_layout = us,br

    ## Variants
    kb_variant = ,abnt2

    ## Bind to switch layout
    kb_options = grp:alt_shift_toggle

    # Mouse
    ## Acceleration profile
    accel_profile = flat

    ## Follow mouse (specify if and how cursor movement should affect window focus)
    follow_mouse = 1

    ## Sensitivity
    sensitivity = 0
}
